import Head from "next/head";

import Hero from "../component/Hero";
import List from "../component/Repositories/List.repositories";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <List />
      </main>

      <footer></footer>
    </div>
  );
}
